language: go
go:
  - 1.9
go_import_path: github.com/kubeapps/kubeapps
sudo: required

addons:
  apt:
    packages:
      # cross compiling for windows
      - mingw-w64

env:
  global:
  - VERSION=${TRAVIS_TAG:-build-$TRAVIS_BUILD_ID}
  - GO_XFLAGS=""

install:
- |
  if ! which kubecfg; then
    wget -O kubecfg https://github.com/ksonnet/kubecfg/releases/download/v0.7.2/kubecfg-$(go env GOOS)-$(go env GOARCH)
    install -m 755 kubecfg $GOPATH/bin/kubecfg
  fi

jobs:
  include:
  - stage: test
    script: make test

  # 3 parallel build stage jobs for cross-compilation
  - stage: build
    env: PLATFORM=linux-amd64
    script: make VERSION="$VERSION" kubeapps-$PLATFORM
  - stage: build
    env: PLATFORM=darwin-amd64
    script: make VERSION="$VERSION" osxcross kubeapps-$PLATFORM
  - stage: build
    env: PLATFORM=windows-amd64
    script: make VERSION="$VERSION" GO_XFLAGS="-ldflags='-extldflags \"-static\"'" kubeapps-$PLATFORM
