---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sealedsecrets.bitnami.com
spec:
  group: bitnami.com
  names:
    kind: SealedSecret
    listKind: SealedSecretList
    plural: sealedsecrets
    singular: sealedsecret
  scope: Namespaced
  validation:
    openAPIV3Schema:
      $schema: http://json-schema.org/draft-04/schema#
      description: A sealed (encrypted) Secret
      properties:
        spec:
          properties:
            data:
              pattern: ^[^A-Za-z0-9+/=]*$
              type: string
          type: object
      type: object
  version: v1alpha1
